### ISSUE TITLE
reset the MCTS during self-play

### ISSUE THREAD

**Issue by hharryyf** [initial-h/AlphaZero_Gomoku_MPI#42]
Hi, in line 391 of game_board.py, I see you reset the MCTS when the self-play game terminates. I know this is exactly the same code in the referenced repo https://github.com/junxiaosong/AlphaZero_Gomoku. However, is this really the expected behavior? You reset the search tree after every single self-play game? Should you remove this line instead? And reset the search tree after every K self-play games (K is large enough to ensure you'll not exceed the memory limit)? Because if you reset the search tree after every single self-play game, you'll lose a lot of useful information stored in the search tree that might be useful for future games.

https://github.com/initial-h/AlphaZero_Gomoku_MPI/blob/95867cb7e524ebe9c77a926c82091785693c3c0a/game_board.py#L391

**Comment by initial-h** [comment]
Hi, at each step, the search tree will discard all parents to save memory. The tree only maintains nodes from the current state. If you want to maintain a tree for multiple self-play games, you need to store all states that start from the empty board, this will consume much more memory which is not practical. And since at each tree building and node expansion step, the network gives new probabilities and values, if the tree is maintained for multiple games, these values will be the same for these games, which are worse than values given by a newly updated network.

**Comment by hharryyf** [comment]
Thanks a lot for your reply!
